<a href="https://colab.research.google.com/github/Samuel-1302/Teste-de-software/blob/main/Samuel_e_Mayane_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt

In [ ]:
df_2000 = pd.read_csv("/gasolina_2000_.csv")
df_2010 = pd.read_csv("/gasolina_2010_.csv")

/tmp/ipykernel_627/1724917543.py:2: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2010 = pd.read_csv("/gasolina_2010_.csv")

In [ ]:
df = pd.concat([df_2000,df_2010], ignore_index=True)

In [ ]:
df.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  object
 2   DATA FINAL                     120823 non-null  object
 3   REGIÃO                         120823 non-null  object
 4   ESTADO                         120823 non-null  object
 5   PRODUTO                        120823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  object
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(2), object(12)
memory usage: 17.5+ MB

In [ ]:
df.iloc[2, 1]

'2004-05-09'

In [ ]:
(type(df.iloc[2, 1]))

str

In [ ]:
df['DATA INICIAL'] = pd.to_datetime(df['DATA INICIAL'])
df['DATA FINAL'] = pd.to_datetime(df['DATA FINAL'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     120823 non-null  int64
 1   DATA INICIAL                   120823 non-null  datetime64[ns]
 2   DATA FINAL                     120823 non-null  datetime64[ns]
 3   REGIÃO                         120823 non-null  object
 4   ESTADO                         120823 non-null  object
 5   PRODUTO                        120823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 7   UNIDADE DE MEDIDA              120823 non-null  object
 8   PREÇO MÉDIO REVENDA            120823 non-null  float64
 9   DESVIO PADRÃO REVENDA          120823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           120823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 12  MARGEM MÉDIA REVENDA           120823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(10)
memory usage: 17.5+ MB

In [ ]:
df['ANO-MES'] = df['DATA FINAL'].dt.strftime('%Y-%m')

In [ ]:
df['ANO-MES']

0         2004-05
1         2004-05
2         2004-05
3         2004-05
4         2004-05
           ...
120818    2021-05
120819    2021-05
120820    2021-05
120821    2021-05
120822    2021-05
Name: ANO-MES, Length: 120823, dtype: object

In [ ]:
df['PRODUTO'].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [ ]:
gasolina_comum = df[df['PRODUTO'] == 'GASOLINA COMUM']

In [ ]:
gasolina_comum.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
9256,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.99,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
9257,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.85,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
9258,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.00,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
9259,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.97,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
9260,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.00,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05

In [ ]:
df[df['ANO-MES'] == '2008-08']['PREÇO MÉDIO REVENDA'].mean()

np.float64(9.300789303079416)

In [ ]:
df['ANO-MES'].value_counts()

ANO-MES
2021-01    878
2014-03    764
2014-08    764
2013-11    763
2014-11    763
          ...
2009-08    373
2004-05    369
2020-10    349
2005-08    249
2021-05    178
Name: count, Length: 204, dtype: int64

In [ ]:
df['ESTADO'].value_counts()

ESTADO
BAHIA                  4819
PARAIBA                4819
SAO PAULO              4819
RIO GRANDE DO SUL      4819
RIO DE JANEIRO         4819
RIO GRANDE DO NORTE    4818
SANTA CATARINA         4818
MINAS GERAIS           4817
ESPIRITO SANTO         4815
CEARA                  4813
PERNAMBUCO             4813
PARANA                 4807
ALAGOAS                4806
SERGIPE                4795
MATO GROSSO DO SUL     4793
MATO GROSSO            4566
AMAZONAS               4414
GOIAS                  4134
PIAUI                  4017
MARANHAO               3971
DISTRITO FEDERAL       3956
PARA                   3955
TOCANTINS              3953
RONDONIA               3950
ACRE                   3948
RORAIMA                3938
AMAPA                  3831
Name: count, dtype: int64

In [ ]:
df[(df['ANO-MES'] == '2014-05') & (df['ESTADO'] == 'SAO PAULO')]['PREÇO MÉDIO REVENDA'].mean()

np.float64(8.920766666666669)

In [ ]:
acima_5 = df[df['PREÇO MÉDIO REVENDA'] > 5]

In [ ]:
acima_5['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [ ]:
acima_5[['ESTADO', 'ANO-MES', 'PREÇO MÉDIO REVENDA']]

                    ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
18516     DISTRITO FEDERAL  2004-05               33.989
18517                GOIAS  2004-05               30.335
18518          MATO GROSSO  2004-05               38.568
18519   MATO GROSSO DO SUL  2004-05               33.388
18520              ALAGOAS  2004-05               32.391
...                    ...      ...                  ...
120750           SAO PAULO  2021-05               85.340
120751             SERGIPE  2021-05               83.508
120752           TOCANTINS  2021-05               93.867
120769                ACRE  2021-05                5.550
120796                ACRE  2021-05                5.209

[24304 rows x 3 columns]

In [ ]:
df['REGIÃO'].unique()

array(['CENTRO OESTE', 'NORDESTE', 'NORTE', 'SUDESTE', 'SUL'],
      dtype=object)

In [ ]:
df[(df['DATA FINAL'].dt.year == 2012) & (df['REGIÃO'] == 'SUL')]['PREÇO MÉDIO REVENDA'].mean()

np.float64(9.842052564102564)

In [ ]:
df['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [ ]:
rj = df[df['ESTADO'] == 'RIO DE JANEIRO']

In [ ]:
(rj.groupby(rj['DATA FINAL'].dt.year)['PREÇO MÉDIO REVENDA'].mean().pct_change() * 100)

DATA FINAL
2004          NaN
2005     2.005140
2006     6.748521
2007     1.823992
2008     0.880040
2009     5.795120
2010    10.000780
2011     0.748688
2012     0.783907
2013    -9.159533
2014     7.359483
2015     9.623959
2016    10.173577
2017    10.002523
2018    11.829930
2019     2.813888
2020    -3.469336
2021     5.236270
Name: PREÇO MÉDIO REVENDA, dtype: float64